from __future__ import annotations
from typing import Any
from psyflow import StimUnit,next_trial_id,set_trial_context
from .utils import LETTERS,SetPlan
def _ctx(u,tid,bid,p,phase,deadline,keys,stim,extra=None): set_trial_context(u,trial_id=tid,phase=phase,deadline_s=deadline,valid_keys=keys,block_id=bid,condition_id=str(p),task_factors={**p.to_dict(),"stage":phase,**(extra or {})},stim_id=stim)
def run_trial(win,kb,settings,condition,stim_bank,trigger_runtime,block_id=None,block_idx=None):
    if not isinstance(condition,SetPlan): raise TypeError("OSPAN requires SetPlan")
    p=condition; tid=next_trial_id(); bid=str(block_id or "scored"); data={"trial_id":tid,"phase":"set_recall","block_id":bid,"block_idx":int(block_idx or 0),**p.to_dict()}; solve_rts=[]; math_correct=0
    for i,item in enumerate(p.items):
        solve=StimUnit(f"solve_{i+1:02d}",win,kb,runtime=trigger_runtime).add_stim(stim_bank.get_and_format("operation",expression=item["expression"])); _ctx(solve,tid,bid,p,"solve",float(settings.solve_window),["space"],"operation"); solve.capture_response(keys=["space"],duration=float(settings.solve_window),onset_trigger=settings.triggers.get("operation"),timeout_trigger=settings.triggers.get("timeout"),terminate_on_response=True).to_dict(data); rt=solve.get_state("rt",None); solve_rts.append(float(rt) if rt is not None else float(settings.solve_window))
        verify=StimUnit(f"verify_{i+1:02d}",win,kb,runtime=trigger_runtime).add_stim(stim_bank.get_and_format("verification",expression=item["expression"],proposed=item["proposed"])); _ctx(verify,tid,bid,p,"verification",float(settings.math_deadline),["f","j"],"verification",{"correct_key":item["math_correct_key"]}); verify.capture_response(keys=["f","j"],correct_keys=[item["math_correct_key"]],duration=float(settings.math_deadline),onset_trigger=settings.triggers.get("verification"),response_trigger={"f":settings.triggers.get("false_response"),"j":settings.triggers.get("true_response")},timeout_trigger=settings.triggers.get("timeout"),terminate_on_response=True).to_dict(data); math_correct+=int(verify.get_state("response",None)==item["math_correct_key"])
        if p.set_size>0:
            letter=StimUnit(f"letter_{i+1:02d}",win,kb,runtime=trigger_runtime).add_stim(stim_bank.rebuild("letter",text=item["letter"])); _ctx(letter,tid,bid,p,"letter",float(settings.letter_duration),[],item["letter"]); letter.show(duration=float(settings.letter_duration),onset_trigger=settings.triggers.get("letter")).to_dict(data)
    recalled=[]
    if p.set_size>0:
        for i in range(p.set_size):
            recall=StimUnit(f"recall_{i+1:02d}",win,kb,runtime=trigger_runtime).add_stim(stim_bank.get_and_format("recall",position=i+1,set_size=p.set_size,chosen=" ".join(recalled) or "-")); keys=[x.lower() for x in LETTERS]; _ctx(recall,tid,bid,p,"recall",float(settings.recall_window),keys,"recall",{"correct_key":p.items[i]["letter"].lower()}); recall.capture_response(keys=keys,correct_keys=[p.items[i]["letter"].lower()],duration=float(settings.recall_window),onset_trigger=settings.triggers.get("recall"),response_trigger=settings.triggers.get("letter_response"),timeout_trigger=settings.triggers.get("timeout"),terminate_on_response=True).to_dict(data); recalled.append(str(recall.get_state("response","") or "").upper())
        correct=sum(a==b["letter"] for a,b in zip(recalled,p.items)); fb=StimUnit("set_feedback",win,kb,runtime=trigger_runtime).add_stim(stim_bank.get_and_format("feedback",correct=correct,total=p.set_size,math=math_correct,math_total=p.set_size)); set_trial_context(fb,trial_id=tid,phase="feedback",deadline_s=float(settings.feedback_duration),valid_keys=[],block_id=bid,condition_id=str(p),task_factors={**p.to_dict(),"stage":"feedback"},stim_id="feedback"); fb.show(duration=float(settings.feedback_duration),onset_trigger=settings.triggers.get("feedback")).to_dict(data)
    else: correct=0
    data.update(solve_mean_rt=sum(solve_rts)/len(solve_rts),math_count=len(p.items),math_correct=math_correct,math_accuracy=math_correct/len(p.items),recalled_letters=recalled,letters_correct=correct,perfect_recall=correct==p.set_size if p.set_size else False,outcome="complete"); return data
